### ISSUE TITLE
Feature Request: Support Adobe Connect

### ISSUE THREAD

**Issue by AlistairKeiller** [Leko/crx-gcal-url-opener#52]

**Comment by Leko** [comment]
@AlistairKeiller Can you provide an example URL of the Adobe Connect meeting?

**Comment by AlistairKeiller** [comment]
The main scheme is https://pcadobeconnect.hosting.example/roomID, where hosting.example would change depending on who is hosting it ( for me it is the domain of my educational institution ).

**Comment by Leko** [comment]
Closed in https://github.com/Leko/crx-gcal-url-opener/tree/v1.2.0
